# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11d86a8a936b4d8069ee4f9dda509c00c39942504062b5504c3e01a021998f2bf3fcef45e15a3e7a5edf45f7bdb01390e3766ffe249164cf30eaefe25b94d39e

test:
  secret_key_base: 703233a69f57156e4020cfb7b262f7abccda20195d12b10b804f92e7df9180569d0a01fc2dcc5b5bb29a5956b06c5724a7d6a4a98f0a3251ebc602e08eb836d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
